### ISSUE TITLE
Self-hosting guide?

### ISSUE THREAD

**Issue by Codeize** [MenuDocs/Mandroc#34]
It could potentially expand the radius of appeal for the project if a self-hosting/installation guide is provided in the README. Maybe you all think differently? Lmk :)

**Comment by Codeize** [comment]
Yes you won't provide support for it, but possibly provide a guide and make it clear if you run into issues no support whatsoever will be provided.

**Comment by melike2d** [comment]
Here's your installation guide.

- `yarn`

**Comment by Strandxo** [comment]
There will be a BASIC setup guide provided so that people can run the code whilst working on helping develop said code however we WONT be providing a self hosting guide as this code is not for private usage, thanks.
